local builtin_themes = {
    ['blue'] = true,
    ['darkblue'] = true,
    ['default'] = true,
    ['delek'] = true,
    ['desert'] = true,
    ['elflord'] = true,
    ['evening'] = true,
    ['habamax'] = true,
    ['industry'] = true,
    ['koehler'] = true,
    ['lunaperche'] = true,
    ['morning'] = true,
    ['murphy'] = true,
    ['pablo'] = true,
    ['peachpuff'] = true,
    ['quiet'] = true,
    ['retrobox'] = true,
    ['ron'] = true,
    ['shine'] = true,
    ['slate'] = true,
    ['sorbet'] = true,
    ['torte'] = true,
    ['vim'] = true,
    ['wildcharm'] = true,
    ['zaibatsu'] = true,
    ['zellner'] = true,
}

return builtin_themes
